databases:
  - name: portfolio
    databaseName: portfolio
    user: Portfolio
    region: singapore

services:
  - type: web
    name: Portfolio
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: Asia/Tokyo
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    ports:
      - number: 3000 

