databases:
  - name: portfolio
    databaseName: portfolio
    user: Portfolio
    region: singapore

services:
  - type: web
    name: Portfolio
    env: docker
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    ports:
      - number: 3000 #追加

services:
  - name: sidekiq
    environment:
      SIDEKIQ_CONCURRENCY: 10
      REDIS_URL: redis://red-cpr64c3qf0us7389fk9g:6379/0
    ports:
      - port: 6379
        protocol: tcp